# Generated by Django 4.0 on 2022-01-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kinddetail',
            table='kind_detail',
        ),
    ]
