# Generated by Django 4.0 on 2022-01-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_kinddetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='invoice',
        ),
    ]
