# Generated by Django 4.0 on 2021-12-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuit', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('clienteCode', models.CharField(max_length=100)),
            ],
        ),
    ]
