# Generated by Django 4.0 on 2022-01-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_cuit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cuit',
        ),
    ]
