# Generated by Django 4.0 on 2022-01-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_cuit'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cuit',
            field=models.PositiveBigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
