# Generated by Django 4.0 on 2022-01-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_cuit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='clienteCode',
            new_name='clientCode',
        ),
        migrations.AlterField(
            model_name='client',
            name='cuit',
            field=models.BigIntegerField(),
        ),
    ]
